sudo: required
dist: trusty
language: node_js
node_js: 7
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  app:
    master: quoridor-jees
    develop: jees-quoridor
  api_key:
    master:
      secure: t6wC54YyE985ljPMNNwykkd+3Jrpfzuo4tN+5h9+AIh9jlPIW5RagmoeKqhF6dFUA/DXRNNGlb7TiXykVoLMnnD+a+fH2me+dfSspLGMae+vxdOEpfhkgyPOtCoJUfZmsvq+zo2asnz7uSFdpmsQU8zIaFGy8okI/36eSosG0wKjGfCa0AZynkf0JggjB2VBgr2YcL0rN2/jSLn4zdLiWaoUZBw2F9UyLKVbK4i+5Jx4/Ffxtzh17LxEQnPb90T/Lkemc7ucs4U5PeFAag9Z0LBz6p4B1BWquFCo4dzTA3QZ0wzkpiVbNCWsk4RfXKkr7WKxwOmBm+6+K4EgX1nr/NNVCwkuGsF1rHRDPD08MUcFzWCEf8b3XUjYM9U41GMol+wxrbOSVIF/WFyegHqye8TeRjqhYcjBq6jVKIj3UmxgaaVH0LYeobKZonSynAZaKlUrPI8OGKj50W34P8BQks/Zr9wr25RQE5YyWeWCdSxGOEi9odc2KbsRbr7wh7V/ubMihsjDqxMmmGi40AJpJZxLNGGJvR0Ysn30ASTPooKoEOvBrymcVncDEg4a5h8DrF8pt6EI/s7ULFhKFqyS11tD/+8/TyGHEq25qRrLcJKd4bPHUQdPzNeN/rOGH8beAVuL1+9Ag2x2zZizzP3R44wKUjMwuxJElgNE6NoWa4g=
    develop:
      secure: RL+gzdSxuzvas7fKI3sKgkKXn63TKg74EuU5Fa4wPfEL+sj36/hy9cDeJvqAG6wtsNQEsb8dznllaCvjcMyOt+LBLs97RPJ9CYlW6vZ2Hk82zo6mNQvSm9HmfckIVne4reEYqt7VTZe4IvKmJQ+fDDJ/gch84rqZPHtbqmQdwHSAROq5pJw5e6xhJYZVTX0FUy7NJKQi6EBGgENPxEJMD2rY8xidOfAdjWvEEk6o4tmRiTGKLaloZ5kc6TRL6jfmHjeuaLSnxoRexXgdjqHNp+Elu8YYjIvw5Oi7C17mN8l2oHLjfHbEZQ05/hHqPln+rzGWmv4QEcGZtkk3gOH9cKYOQONKo3q3HpztfhOcKEvnE43ecY88D5UjmNOGtgcg199b7RjGz02zZTBDHKnueqS6ej1RKUuBjF8pAVTP1i9naVTjTJzlcPO67KGsJgn6YXmHtl+PFNQgcvReXnIcLEsRHGOVB5NtDf+nOjl2YM8BvTSfXWZhqMNsh+GaPVcDn+56OOZWiYXhXmRJNboXrcxbvqyOjGYMhaj3hNGMN4Gc9+xqv8pAM+/vEwAEYZJdXZQf5W+bT3e1x60+Go/7T6Cr3U8xUJcnxsCBaka9GqBWfuYrbZZHSKc42qcKaISlw3g+i+dY/rYDDJDrONp5DoXfhTECX59hNjhFO5JADWU=
